name: Linter

on:
    push:
        branches: [master]
        paths-ignore:
            - "**.md"

    pull_request:
        types: [opened, reopened, synchronize]
    release:
        types: [published]

jobs:
    cpp-linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: github/super-linter@v4.8.1
              env:
                  VALIDATE_ALL_CODEBASE: true
                  DEFAULT_BRANCH: master
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
